spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
##配置redis缓存管理器
  cache:
    type: redis
    ##配置缓存的名称，多个名称使用逗号分隔，以便于缓存注解的引用
    cache-names: redisCache

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.learn.springboot.mybatis.entity
  config-location: classpath:mybatis-config.xml
